FROM maven:3.6.3-jdk-11 AS MAVEN_BUILD
 
# copy the pom and src code to the container
COPY ./ ./
 
# package our application code
RUN mvn clean package
 
# the second stage of our build will use open jdk 11 on alpine
FROM openjdk:11-jre
 
# copy only the artifacts we need from the first stage and discard the rest
COPY --from=MAVEN_BUILD /target/currency-exchange-service-0.0.1-SNAPSHOT.jar /currency-exchange-service.jar
 
# set the startup command to execute the jar
CMD ["java", "-jar", "/currency-exchange-service.jar"]

##https://codefresh.io/docker-tutorial/create-docker-images-for-java/
